development:
  adapter: postgresql
  encoding: utf8
  database: rais_ops_web_db_dev
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rais_ops_web_db_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: rais_ops_web_db
  pool: 5
  username: 
  password:
