# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99eb2705de004f8164d5d31bea2353c4a22356b5d2b98c69c1c7bc1c4d10d25772939d2f2e44b1a8eb261349e5bbe011cf44697344589b87d1d6f7a66e5fc24

test:
  secret_key_base: ad197b5937328c5f348667bf5e5d2bc146667b575ff3bd13b02a28b0eed00921c4b5cc25398ba1f0e09fa540b3f32386f46d1eb22d2717514999d4e7171a982f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
